server:
  #  port: 443
  port: 8080
#  ssl:
#    key-store: classpath:214955751900154.pfx
#    key-store-type: PKCS12
#    key-store-password: 214955751900154

#thymeleaf start
spring:
  application:
    name: pic-server
#thymeleaf end
  datasource:
       name: task
    #       url:
       url:
       username:
       password:
       # 使用druid数据源
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       filters: stat
       # 初始化大小，最小，最大
       initialSize: 5
       minIdle: 5
       maxActive: 20
       # 配置获取连接等待超时的时间
       maxWait: 60000
       # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
       timeBetweenEvictionRunsMillis: 60000
       # 配置一个连接在池中最小生存的时间，单位是毫秒
       minEvictableIdleTimeMillis: 300000
       validationQuery: SELECT 1 FROM DUAL
       testWhileIdle: true
       testOnBorrow: false
       testOnReturn: false
       # 打开PSCache，并且指定每个连接上PSCache的大小
       poolPreparedStatements: true
       maxPoolPreparedStatementPerConnectionSize: 20



mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.megatron.picserver.pojo



#在application.properties文件中引入日志配置文件
#=====================================  log  =============================
logging:
  config: classpath:logback-boot.xml


#IMAGE_PATH: D:\file\
IMAGE_PATH: /data/temp

file.server.path:


appId:

secret:








